### ISSUE TITLE
不知道为啥，点任何一个选项都是无法获得下载连接

### ISSUE THREAD

**Issue by Tz-gun** [Hatsune-Miku-001/baidudrive#1]
网址：https://yun.baidu.com/disk/main?from=homeFlow#/index?category=all&path=%2F
控制台
content.js:2941 Uncaught (in promise) Error: Corruption: block checksum mismatch
    at wrappedSendMessageCallback (content.js:2941:18)
wrappedSendMessageCallback @ content.js:2941
await in wrappedSendMessageCallback（异步）
（匿名） @ content.js:3716
（匿名） @ content.js:3718
（匿名） @ content.js:3720
userscript.html?name=%25E7%2599%25BE%25E5%25BA%25A6%25E7%25BD%2591%25E7%259B%2598%25E7%25AE%2580%25E6%2598%2593%25E4%25B8%258B%25E8%25BD%25BD%25E5%258A%25A9%25E6%2589%258B%25EF%25BC%2588%25E7%259B%25B4%25E9%2593%25BE%25E4%25B8%258B%25E8%25BD%25BD%25E5%25A4%258D%25E6%25B4%25BB%25E7%2589%2588%25EF%25BC%2589.user.js&id=4faa607d-6260-431e-89c9-065ab8a1fef4:11996 脚本开始
chunk-04d8843d.9ac78393.js:1 [Plugin][uploader] created
chunk-04d8843d.9ac78393.js:1 undefined
userscript.html?name=%25E7%25BD%2591%25E7%259B%2598%25E7%259B%25B4%25E9%2593%25BE%25E4%25B8%258B%25E8%25BD%25BD%25E5%258A%25A9%25E6%2589%258B-%25E5%2585%258D%25E5%2585%25B3%25E6%25B3%25A8!!!.user.js&id=095df90d-b506-4d64-ac6c-ce77b085870a:122 [网盘直链下载助手-免关注!!!]
userscript.html?name=%25E7%25BD%2591%25E7%259B%2598%25E7%259B%25B4%25E9%2593%25BE%25E4%25B8%258B%25E8%25BD%25BD%25E5%258A%25A9%25E6%2589%258B-%25E5%2585%258D%25E5%2585%25B3%25E6%25B3%25A8!!!.user.js&id=095df90d-b506-4d64-ac6c-ce77b085870a:123 助手加载成功！版本：5.8.4
main?from=homeFlow:306          GET https://yun.baidu.com/static/js/file.min.js 404 (Not Found)
nd_bundle_430546.js?t=1657162915631:5 jnqp error
nd_bundle_430546.js?t=1657162915631:5 jnqp error
nd_bundle_430546.js?t=1657162915631:5 {"errno":0,"errmsg":"success","request_id":8959405027124006105}

**Comment by Hatsune-Miku-001** [comment]
该插件仅在分享链接内有效
